[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor --chip esp32c6"
rustflags = [
  "-C",
  "link-arg=-Tlinkall.x",      # Includes memory.x + regions + trap setup
  "-C",
  "link-arg=--fatal-warnings", # Optional: stricter linking
  "-C",
  "force-frame-pointers=yes",  # Recommended for backtraces
]
[env]

[build]
rustflags = [
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C",
  "force-frame-pointers",
]

target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]
