name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust + RISC-V target
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: riscv32imac-unknown-none-elf

      - uses: Swatinem/rust-cache@v2

      - name: Format
        run: cargo fmt --all -- --check

      - name: Check
        run: |
          cargo check --features sync
          cargo check --features async 

      - name: Check (Examples)
        working-directory: examples/esp32
        run: |
          cargo check --release --features esp32c6,sync --target riscv32imac-unknown-none-elf
          cargo check --release --features esp32c6,async --target riscv32imac-unknown-none-elf

      - name: Clippy
        run: |
          cargo clippy --features sync -- -D clippy::pedantic
          cargo clippy --features async -- -D clippy::pedantic

      - name: Clippy (Examples)
        working-directory: examples/esp32
        run: |
          cargo clippy --example simple --release --features esp32c6,sync --target riscv32imac-unknown-none-elf -- -D clippy::pedantic
          cargo clippy --example simple_async --release --features esp32c6,async --target riscv32imac-unknown-none-elf -- -D clippy::pedantic

      - name: Build
        run: |
          cargo build --features sync
          cargo build --features async

      - name: Build (Examples)
        working-directory: examples/esp32
        run: |
          cargo build --example simple --release --features esp32c6,sync --target riscv32imac-unknown-none-elf
          cargo build --example simple_async --release --features esp32c6,async --target riscv32imac-unknown-none-elf

      - name: Run tests
        run: cargo +stable test --features=test --verbose

      - name: Docs
        run: cargo doc --no-deps --features async
